name: Test Bindings

on:
  workflow_call:
    secrets:
      BOT_ACCESS_TOKEN:
        required: true
      ONSHAPE_API_ACCESS_KEY:
        required: true
      ONSHAPE_API_SECRET_KEY:
        required: true
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v3.2.0
        with:
          go-version: '1.20'
      - name: Run all tests
        run: |
         export ONSHAPE_BASE_URL=https://demo-c.dev.onshape.com
         export ONSHAPE_API_ACCESS_KEY=${{ secrets.ONSHAPE_API_ACCESS_KEY }}
         export ONSHAPE_API_SECRET_KEY=${{ secrets.ONSHAPE_API_SECRET_KEY }}

         git config user.name github-actions
         git config user.email github-actions@github.com

         go get -u ${{ github.workspace }}/...
         go mod tidy
         if [[ $(git status --porcelain go.mod go.sum) ]]; then
            git add go.mod go.sum
            git commit -m "Update go mods"
            git push
         fi

         go test ${{ github.workspace }}/...
