name: Test Bindings

on:
  pull_request:
    types: [opened, reopened, edited]
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v3.2.0
        with:
          go-version: 1.18.3
      - name: Run all tests
        run: |
         export ONSHAPE_API_ACCESS_KEY=${{ secrets.ONSHAPE_API_ACCESS_KEY }}
         export ONSHAPE_API_SECRET_KEY=${{ secrets.ONSHAPE_API_SECRET_KEY }}
         go test ${{ github.workspace }}/...
